server:
  port: 8081
# dev 开发环境 prod 线上环境
spring:
  application:
    name: pre
  profiles:
    active: dev
  servlet:
      multipart:
        file-size-threshold: 0
        max-file-size: 100MB      #上传单个文件最大字节数
        max-request-size: 100MB
        enabled: true #上传文件总数的最大字节数
        location: D:/springWorkSpace/files/
